language: java

services:
  - docker
  
# docker cache stuff is from https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-248915326
cache:
  directories:
  - docker_images

before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)
  

before_install:
  - docker load -i docker_images/images.tar || true
  
  - pushd docker
  - docker-compose build
  - popd
  
script:
  - pushd docker
  - # docker-compose up #disabled as this step hangs
  - popd