version: '3'
services:
  webserver:
    build:
      context: ./
      dockerfile: ./containers/webserver/Dockerfile
    ports:
      - "5001:5001"
  database:
    build:
      context: ./
      dockerfile: ./containers/database/Dockerfile