version: '3'
services:
  storage:
    build:
      context: ./
      dockerfile: ./containers/storage/Dockerfile
  webserver:
    build:
      context: ./
      dockerfile: ./containers/webserver/Dockerfile
    ports:
      - "5001:5001"
  database:
    build:
      context: ./
      dockerfile: ./containers/database/Dockerfile
    env_file: database.env